branches:
  only: master
deploy:
  api_key: $API_KEY
  email: gcca.00@gmail.com
  provider: npm
  skip_cleanup: true
git:
  depth: 2
  lfs_skip_smudge: true
language: node_js
node_js: '7'
